#!/bin/sh
# Record the current build and connected mouse without replaying sample output.
set -eu

project_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
cd "$project_root"

for dependency in cargo vhs ffmpeg; do
    if ! command -v "$dependency" >/dev/null 2>&1; then
        printf 'Required command not found: %s\n' "$dependency" >&2
        exit 1
    fi
done

cargo build --release --locked
binary="$project_root/target/release/gbat"
version=$("$binary" --version)
printf 'Recording %s\n' "$version"
# Fail before recording if the mouse cannot provide a real battery reading.
"$binary"

work_dir=$(mktemp -d "$project_root/target/record-demo.XXXXXX")
trap 'rm -r "$work_dir"' EXIT
trap 'exit 1' HUP INT TERM
frames="$work_dir/frames"
candidate="$work_dir/demo.gif"

# VHS 0.12.0 cancels its render context before starting FFmpeg. Keep its PNG
# frames and render separately. A temporary GIF output also makes VHS generate
# bar.png and mask.png; no tape output can overwrite the published GIF.
awk -v frames="$frames" -v video="$work_dir/vhs.gif" '
    /^[[:space:]]*Output[[:space:]]/ {
        if (!replaced) {
            print "Output \"" video "\""
            print "Output \"" frames "/\""
            replaced = 1
        }
        next
    }
    { print }
    END { if (!replaced) exit 1 }
' demo.tape > "$work_dir/demo.tape"
vhs "$work_dir/demo.tape"

# Match demo.tape: 1100x500, 30 fps, 24 px padding, a 30 px window bar,
# Catppuccin Mocha background, and the border mask generated by VHS.
ffmpeg -hide_banner -loglevel error -y \
    -framerate 30 -start_number 1 -i "$frames/frame-text-%05d.png" \
    -framerate 30 -start_number 1 -i "$frames/frame-cursor-%05d.png" \
    -f lavfi -i 'color=#1e1e2e:s=1100x500:r=30' \
    -framerate 30 -i "$frames/bar.png" \
    -framerate 30 -i "$frames/mask.png" \
    -filter_complex '
        [0][1]overlay[merged];
        [merged]scale=1052:422:force_original_aspect_ratio=1[scaled];
        [scaled]fps=30,setpts=PTS/1.0[speed];
        [speed]pad=1100:470:(ow-iw)/2:(oh-ih)/2:#1e1e2e[padded];
        [padded]fillborders=left=24:right=24:top=24:bottom=24:mode=fixed:color=#1e1e2e[filled];
        [3]loop=-1:size=1[loopbar];
        [loopbar][filled]overlay=0:30:shortest=1[withbar];
        [4]loop=-1:size=1[loopmask];
        [withbar][loopmask]alphamerge=shortest=1[rounded];
        [2]scale=1100:500[bg];
        [bg][rounded]overlay=(W-w)/2:(H-h)/2:shortest=1[withbg];
        [withbg]split[plt_a][plt_b];
        [plt_a]palettegen=max_colors=256[plt];
        [plt_b][plt]paletteuse[palette]
    ' \
    -map '[palette]' "$candidate"

test -s "$candidate"
ffmpeg -hide_banner -loglevel error -xerror -i "$candidate" -f null -
cp "$candidate" "$project_root/assets/demo.gif"
printf 'Recorded %s in %s\n' "$version" "$project_root/assets/demo.gif"
